### ISSUE TITLE
[Feature] Mock Jest assertions that test uploading to Cloudinary

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/netlify-plugin-cloudinary#31]
## **Is your feature request related to a problem? Please describe.**

We want to be able to test the functions that upload images to Cloudinary without actually uploading them.

## **Describe the solution you'd like**

Mocking whatever functions need to be mocked in order to prevent uploads while still testing the plugin capability

### **Additional context**

Commented out after updating to test strings for creating tests on https://github.com/colbyfayock/netlify-plugin-cloudinary/pull/30

SSee the following test cases:
* should create a Cloudinary URL with delivery type of upload from a local image
* should create a Cloudinary URL with delivery type of upload from a remote image

**Comment by colbyfayock** [comment]
@matiasfha is this considered complete with the work you did already?

**Comment by matiasfha** [comment]
I think it does
