### ISSUE TITLE
[Feature] Concurrent uploads limited to 10 at a time

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/netlify-plugin-cloudinary#57]
# **Feature Request**

## **Is your feature request related to a problem? Please describe.**

Uploads should be made concurrently and configurable to higher amounts.

We should add to documentation that enterprise customers are likely the ones who want to increase concurrency as they may hit rate limiting if they raise it on a free or selfserve plan.

## **Describe the solution you'd like**

```
[[plugins]]
  package = "netlify-plugin-visual-diff"
    [plugins.inputs]
      uploadConcurrency = 10
```

Default is 10, but configurable to a higher amount

For the concurrency mechanism, we can use the pLimit package, such as:

```
import pLimit from 'p-limit';
...
const limitUploadFiles = pLimit(4);
...
const uploadsQueue = filesToUpload.map((upload) => {
        return limitUploadFiles(() => {
          async function uploadFile() {
            const imageToUpload = upload as Image;
            const formData = new FormData();

            formData.append('file', imageToUpload.file);

            const results = await fetch('/api/upload', {
              method: 'POST',
              body: formData
            }).then(r => r.json());

            return results
          }
          return uploadFile();
        });
      });

      await Promise.all(uploadsQueue);
```

**Comment by akshay-ranganath** [comment]
For large enterprise migration, we normally run at a concurrency of 40-50. So we should bump this to at least 30.

**Comment by colbyfayock** [comment]
probably make sense to default it to something like 10 and have this configurable though, otherwise it will fail for non-enterprise customers from my understanding
