### ISSUE TITLE
Test failure logging for uploads

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/netlify-plugin-cloudinary#58]
Potential cases:
- Referencing an image that isn't a Cloudinary-supported file (if the node uploader fails)
- Restricting a remote URL from being downloaded through the node uploader (if this is possible)

**Comment by matiasfha** [comment]
@colbyfayock When you say

> Restricting a remote URL from being downloaded through the node uploader (if this is possible)

You mean checking if when it will be about to upload ([here](https://github.com/matiasfha/netlify-plugin-cloudinary/blob/e4f7f6b13c513ab19ee7b98d1e3c43c071e83219/netlify-plugin-cloudinary/src/lib/cloudinary.ts#L164)] Since it is a remote URL, halt/throw and log?

**Comment by colbyfayock** [comment]
@matiasfha no - the idea was to potentially lock down the allowed referrers of the asset so that when trying to download it its not allowed. idk if this would work in practice, but trying to think of ways that the uploader itself will throw the error as thats what we're trying to test
