### ISSUE TITLE
[Feature] Add retry logic for failed uploads

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/netlify-plugin-cloudinary#82]
# **Feature Request**

## **Is your feature request related to a problem? Please describe.**

If an upload fails, we should attempt to re-upload.

Likely would only want to re-attempt that upload once.

**Comment by kcoderhtml** [comment]
Can I do this?

**Comment by kcoderhtml** [comment]
I believe #88 should implement this feature.
