### ISSUE TITLE
[Bug] Production Netlify Integration Does Not Use Latest Version + Minor QOL Suggestions

### ISSUE THREAD

**Issue by gshel** [cloudinary-community/netlify-plugin-cloudinary#93]
# **Bug Report**

## **Describe the bug**

As a Netlify UI user of the publicly available (production) netlify-plugin-cloudinary integration, I am limited to using v1.10.2 ([release](https://github.com/cloudinary-community/netlify-plugin-cloudinary/releases/tag/v1.10.2)/[npm](https://www.npmjs.com/package/netlify-plugin-cloudinary/v/1.10.2)), despite the latest versions being [available](https://www.npmjs.com/package/netlify-plugin-cloudinary).

When a Netlify UI user interacts with the integration's card, the current links do not redirect to the version-specific content.

As a new Netlify UI user, this caused some confusion when I ran into build errors that `maxSize` (available in v1.11.0) was not a valid input.

## **Is this a regression?**

Not sure; I am a new Netlify UI user of this integration.

## **Steps To Reproduce the error**

1. Via the Netlify UI, enable the Cloudinary integration for $site
2. Create a netlify.toml file in $site's root dir
3. Copy/paste the following into netlify.toml + save, commit, push to trigger Netlify deployment:
```
[[plugins]]
  package = "netlify-plugin-cloudinary"

  [plugins.inputs]
  cloudName = "<Your Cloud Name>"

  [plugins.inputs.maxSize]
  height = 800
```
4. Netlify build will fail, complaining of invalid input "maxSize"
5. Review logs to find cloudinary version used, 1.10.2

## **Expected behaviour**

As a Netlify UI user, I had the following incorrect assumptions:

1. Netlify would use the latest available version of the plugin; actual is pinned on v1.10.2
2. Netlify would allow me to specify which version of the plugin to use during build time; actual is possible via the Netlify UI (see Lighthouse integration example in screenshots below), but not specifically for the cloudinary plugin... I was unsuccessful in my attempts to specify the version in my netlify.toml and am unsure if that is possible.
3. Netlify UI Integration Card links would take me to the version-specific content for the version used by Netlify UI:
    * Review changelog: 
        - actual: https://github.com/cloudinary-community/netlify-plugin-cloudinary/releases
        - expected: https://github.com/cloudinary-community/netlify-plugin-cloudinary/releases/tag/v1.10.2
    * Read docs:
        - actual: https://github.com/cloudinary-community/netlify-plugin-cloudinary#readme
        - expected: https://github.com/cloudinary-community/netlify-plugin-cloudinary/tree/v1.10.2#readme

## **Screenshot or Video Recording**

Actual Review changelog link
![image](https://github.com/cloudinary-community/netlify-plugin-cloudinary/assets/35184207/3c42c775-ea73-4cac-a644-667e5b1a026c)

Actual Read docs link
![image](https://github.com/cloudinary-community/netlify-plugin-cloudinary/assets/35184207/a6f75a87-ea07-4ba5-9002-d14e20b07587)

Example of Netlify UI option for changing version
![image](https://github.com/cloudinary-community/netlify-plugin-cloudinary/assets/35184207/0a27e860-7b6a-408f-94b7-1ced79b2cf8b)

netlify.toml does not allow plugin version to be specified, fails build
![image](https://github.com/cloudinary-community/netlify-plugin-cloudinary/assets/35184207/62140703-2880-4dcf-9654-d9da4720f2dc)

netlify.toml plugin input included maxSize, fails build because the version used is 1.10.2, not 1.11.0
![image](https://github.com/cloudinary-community/netlify-plugin-cloudinary/assets/35184207/e64464e1-e5d5-4bdc-bb85-2e1c3e721d64)

### **Your environment**

Netlify UI

- Node version: v18.18.2
- Npm version: v9.8.1
- Netlify build version: @netlify/build 29.25.0

## **Additional context**

Hello and congrats on the latest release! Thanks so much to all the contributors for their time and effort on this project.

I don't have experience publishing public or private integrations on Netlify; the information presented is strictly from a Netlify UI end-user perspective.

**Comment by gshel** [comment]
If there's anything I can do to lend a hand with the issues highlighted, I'm up for it!

**Comment by colbyfayock** [comment]
hey thanks @gshel - part of the issue is i have to manually provide updates to Netlify at the moment for the version to use and admittedly hadn't gotten to providing them with the latest

i just sent them over the latest to update on the site to hopefully get this moving

there used to be a way to manually pin a version but i dont believe that works anymore

will update once its available

**Comment by gshel** [comment]
With the limited digging I was able to do, I was worried this might be the case.

Thanks so much for your assistance!

**Comment by colbyfayock** [comment]
hey @gshel you should now be able to select the enabled version of the plugin in Netlify! 

the default installation isn't the latest (trying to get that fixed) but you can enable it with the dropdown by hitting Change Version

let me know if you run into any issues!

**Comment by gshel** [comment]
It's beautiful 🤩 
Thanks again and hope you have a great weekend~

![image](https://github.com/cloudinary-community/netlify-plugin-cloudinary/assets/35184207/76fc56c5-94e4-4f6d-b0f9-3efb160ddc16)
